---
title: "Basic_NanoSeq_analysis"
output: html_document
date: "2026-02-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading data

```{r}
library(crayon)
Clusters <- read_tsv('C:/Users/rickh/OneDrive - UvA/202511_RickHoogendijk/NanoporeWorkflow/barcode1/Taxonomy.tsv')
Unclassified_species <- Clusters[grep("unclassified", Clusters$Species),]

cat(bold(yellow("\n Number of unclassified species: \n")),length(Unclassified_species$Cluster),bold(yellow("\n Head unclassified species: \n")))
print(head(Unclassified_species))

cat("\n\n",
    green("Adjust cluster number in chunk below to extract fasta of cluster/unclassified bacteria of intrest \n"))

fasta_lines <- readLines('C:/Users/rickh/OneDrive - UvA/202511_RickHoogendijk/NanoporeWorkflow/barcode1/rep_seqs.fasta')

get_cluster_fasta <- function(fasta_lines, cluster_id) {
  
  # Find the header line of the cluster
  start_idx <- grep(paste0("^>", cluster_id, "$"), fasta_lines)
  if (length(start_idx) == 0) return(NULL)
  
  # Find all FASTA headers
  header_idx <- grep("^>", fasta_lines)
  
  # Find the next header after the cluster
  next_header <- header_idx[header_idx > start_idx][1]
  
  # Define end index
  end_idx <- ifelse(
    is.na(next_header),
    length(fasta_lines),
    next_header - 1
  )
  
  fasta_lines[start_idx:end_idx]
}




```

```{r}

cluster_fasta <- get_cluster_fasta(fasta_lines, "Cluster_3")

cat(cluster_fasta, sep = "\n")

```

```{r}
library(readr)
library(tibble)

Family_counts <- read_tsv(
  'C:/Users/rickh/OneDrive - UvA/202511_RickHoogendijk/NanoporeWorkflow/barcode1/Family_counts.tsv',
  show_col_types = FALSE
) %>%
  column_to_rownames(var = colnames(.)[1])


cat(bold(blue("\n Dimensions Family counts: \n")),dim(Family_counts))

Genus_counts <- read_tsv(
  'C:/Users/rickh/OneDrive - UvA/202511_RickHoogendijk/NanoporeWorkflow/barcode1/Genus_counts.tsv',
  show_col_types = FALSE
) %>%
  column_to_rownames(var = colnames(.)[1])


cat(bold(blue("\n Dimensions Genus counts: \n")),dim(Genus_counts))

Species_counts <- read_tsv(
  'C:/Users/rickh/OneDrive - UvA/202511_RickHoogendijk/NanoporeWorkflow/barcode1/Species_counts.tsv',
  show_col_types = FALSE
) %>%
  column_to_rownames(var = colnames(.)[1])


cat(bold(blue("\n Dimensions species counts: \n")),dim(Species_counts))
```

# Calculating relative abundances (RA)

```{r}
# abundance matrix / data frame
# rows = Family, cols = samples
mat <- as.matrix(Family_counts)

# calculate relative abundances per sample
RA_Family <- sweep(mat, 2, colSums(mat, na.rm = TRUE), "/")
```

```{r}
library("tidyverse")
library("vegan")
library("kableExtra")

# Convert to long format
ra_long <- RA_Family %>%
  as.data.frame() %>%
  rownames_to_column("Family") %>%
  pivot_longer(
    cols = -Family,
    names_to = "Run",
    values_to = "Abundance"
  )

# Convert to percent
ra_long <- ra_long %>%
  mutate(Percent = Abundance * 100)

# Group low-abundance species as "Other"
ra_long_grouped <- ra_long %>%
  mutate(
    Family = ifelse(Percent < 1, "Other", Family) #change if needed (is in 100% = 100 not = 1 range)
  ) %>%
  group_by(Run, Family) %>%
  summarize(Percent = sum(Percent), .groups = "drop")

# Reorder factor so Unclassified and Other are last
Family_levels <- unique(ra_long_grouped$Family)
Family_levels <- setdiff(Family_levels, c("Unclassified", "Other"))
Family_levels <- c(Family_levels, "Unclassified", "Other")
ra_long_grouped$Family <- factor(ra_long_grouped$Family, levels = Family_levels)

ggplot(ra_long_grouped, aes(Run, Percent, fill = Family)) +
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Spectral") +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )


```

```{r}
# abundance matrix / data frame
# rows = Genus, cols = samples
mat <- as.matrix(Genus_counts)

# calculate relative abundances per sample
RA_Genus <- sweep(mat, 2, colSums(mat, na.rm = TRUE), "/")
```

```{r}
library("tidyverse")
library("vegan")
library("kableExtra")
library("viridis")

# Convert to long format
ra_long <- RA_Genus %>%
  as.data.frame() %>%
  rownames_to_column("Genus") %>%
  pivot_longer(
    cols = -Genus,
    names_to = "Run",
    values_to = "Abundance"
  )

# Convert to percent
ra_long <- ra_long %>%
  mutate(Percent = Abundance * 100)

# Group low-abundance species as "Other"
ra_long_grouped <- ra_long %>%
  mutate(
    Genus = ifelse(Percent < 5, "Other", Genus) #change if needed (is in 100% = 100 not = 1 range)
  ) %>%
  group_by(Run, Genus) %>%
  summarize(Percent = sum(Percent), .groups = "drop")

# Reorder factor so Unclassified and Other are last
Genus_levels <- unique(ra_long_grouped$Genus)
Genus_levels <- setdiff(Genus_levels, c("Unclassified", "Other"))
Genus_levels <- c(Genus_levels, "Unclassified", "Other")
ra_long_grouped$Genus <- factor(ra_long_grouped$Genus, levels = Genus_levels)

ggplot(ra_long_grouped, aes(Run, Percent, fill = Genus)) +
  geom_bar(stat = "identity") +
  scale_fill_viridis_d(option = "turbo") +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
#scale_fill_brewer(palette = "Spectral") + for less intence collores if not more then 11 families
```

```{r}

# abundance matrix / data frame
# rows = species, cols = samples
mat <- as.matrix(Species_counts)

# calculate relative abundances per sample
RA_species <- sweep(mat, 2, colSums(mat, na.rm = TRUE), "/")

```

```{r}
library("tidyverse")
library("vegan")
library("kableExtra")
library("viridis")

# Convert to long format
ra_long <- RA_species %>%
  as.data.frame() %>%
  rownames_to_column("Species") %>%
  pivot_longer(
    cols = -Species,
    names_to = "Run",
    values_to = "Abundance"
  )

# Convert to percent
ra_long <- ra_long %>%
  mutate(Percent = Abundance * 100)

# Group low-abundance species as "Other"
ra_long_grouped <- ra_long %>%
  mutate(
    Species = ifelse(Percent < 5, "Other", Species) #change if needed (is in 100% = 100 not = 1 range)
  ) %>%
  group_by(Run, Species) %>%
  summarize(Percent = sum(Percent), .groups = "drop")

# Reorder factor so Unclassified and Other are last
species_levels <- unique(ra_long_grouped$Species)
species_levels <- setdiff(species_levels, c("Unclassified", "Other"))
species_levels <- c(species_levels, "Unclassified", "Other")
ra_long_grouped$Species <- factor(ra_long_grouped$Species, levels = species_levels)


ggplot(ra_long_grouped, aes(Run, Percent, fill = Species)) +
  geom_bar(stat = "identity") +
  scale_fill_viridis_d(option = "turbo") +  # discrete colors
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )


```

```{r}
ra_long |>
  group_by(Run) |>
  summarize(total = sum(Percent))
```
